# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3c5256d2430f172f80ff34a78333c6f6cd5e1738def12049684c604abacec9768b0f5859b7a3460a9e733101bbc16e51a6f26d1a830a196a3da2c68495a1777

test:
  secret_key_base: f98509f72882c99b9cae8538c1762fab069da37b4e255e99c8f94e264fa9dfd78eb26007e74dd835db2a14e39cc3b02b053479be4235ab01d6d797db875edc4f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
